/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

/**
 *
 * @author ASUS
 */
public class Dashboard_Admin extends javax.swing.JFrame {

    JDBC stephan;

    /**
     * Creates new form Dashboard
     */
    public Dashboard_Admin() {
        stephan = new JDBC();
        initComponents();
        setLocationRelativeTo(null);
        loadStats();
    }

    private void loadStats() {
        setStat(card_cat, lbl_catValue, "manage_cate");
        setStat(card_pro, lbl_proValue, "manage_pro");
        setStat(card_cus, lbl_cusValue, "customer");
        setStat(card_user, lbl_userValue, "manage_user");
    }

    private void setStat(RoundedPanel card, javax.swing.JLabel valueLabel, String table) {
        try {
            Connection con = stephan.connectdb();
            if (con == null) {
                valueLabel.setText("-");
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT COUNT(*) AS total FROM " + table);
            if (rs.next()) {
                valueLabel.setText(String.valueOf(rs.getInt("total")));
            }
        } catch (Exception e) {
            valueLabel.setText("-");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_sidebar = new javax.swing.JPanel();
        lbl_brand = new javax.swing.JLabel();
        btn_ManageCat = new javax.swing.JButton();
        btn_ManagePro = new javax.swing.JButton();
        btn_manageCus = new javax.swing.JButton();
        btn_manageOrder = new javax.swing.JButton();
        btn_manageUser = new javax.swing.JButton();
        btn_View_order = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        lbl_head = new javax.swing.JLabel();
        lbl_sub = new javax.swing.JLabel();
        card_cat = new RoundedPanel();
        lbl_catValue = new javax.swing.JLabel();
        lbl_catCaption = new javax.swing.JLabel();
        card_pro = new RoundedPanel();
        lbl_proValue = new javax.swing.JLabel();
        lbl_proCaption = new javax.swing.JLabel();
        card_cus = new RoundedPanel();
        lbl_cusValue = new javax.swing.JLabel();
        lbl_cusCaption = new javax.swing.JLabel();
        card_user = new RoundedPanel();
        lbl_userValue = new javax.swing.JLabel();
        lbl_userCaption = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setBackground(Theme.BG);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_sidebar.setBackground(Theme.SIDEBAR);
        pnl_sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_brand.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20));
        lbl_brand.setForeground(java.awt.Color.WHITE);
        lbl_brand.setText("Furniture Co.");
        pnl_sidebar.add(lbl_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 30, 192, 30));

        btn_ManageCat.setText("Category");
        Theme.navButton(btn_ManageCat);
        btn_ManageCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageCatActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_ManageCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 200, 44));

        btn_ManagePro.setText("Product");
        Theme.navButton(btn_ManagePro);
        btn_ManagePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ManageProActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_ManagePro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 152, 200, 44));

        btn_manageCus.setText("Customer");
        Theme.navButton(btn_manageCus);
        btn_manageCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageCusActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_manageCus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 204, 200, 44));

        btn_manageOrder.setText("Order");
        Theme.navButton(btn_manageOrder);
        btn_manageOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageOrderActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_manageOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 256, 200, 44));

        btn_manageUser.setText("User");
        Theme.navButton(btn_manageUser);
        btn_manageUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manageUserActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_manageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 308, 200, 44));

        btn_View_order.setText("View Order");
        Theme.navButton(btn_View_order);
        btn_View_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_View_orderActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_View_order, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, 44));

        btn_logout.setText("Log Out");
        Theme.dangerButton(btn_logout);
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        pnl_sidebar.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 646, 200, 44));

        getContentPane().add(pnl_sidebar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 720));

        lbl_head.setFont(Theme.FONT_TITLE);
        lbl_head.setForeground(Theme.TEXT_DARK);
        lbl_head.setText("Admin Dashboard");
        getContentPane().add(lbl_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 36, 400, 36));

        lbl_sub.setFont(Theme.FONT_BODY);
        lbl_sub.setForeground(Theme.TEXT_MUTED);
        lbl_sub.setText("Here's an overview of your furniture business.");
        getContentPane().add(lbl_sub, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 76, 400, 24));

        card_cat.setPanelColor(new Color(0xFFE8B0));
        card_cat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        lbl_catValue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32));
        lbl_catValue.setForeground(Theme.TEXT_DARK);
        lbl_catValue.setText("0");
        card_cat.add(lbl_catValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));
        lbl_catCaption.setFont(Theme.FONT_LABEL);
        lbl_catCaption.setForeground(Theme.TEXT_DARK);
        lbl_catCaption.setText("Categories");
        card_cat.add(lbl_catCaption, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 160, 22));
        getContentPane().add(card_cat, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 210, 140));

        card_pro.setPanelColor(new Color(0xB9EFEA));
        card_pro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        lbl_proValue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32));
        lbl_proValue.setForeground(Theme.TEXT_DARK);
        lbl_proValue.setText("0");
        card_pro.add(lbl_proValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));
        lbl_proCaption.setFont(Theme.FONT_LABEL);
        lbl_proCaption.setForeground(Theme.TEXT_DARK);
        lbl_proCaption.setText("Products");
        card_pro.add(lbl_proCaption, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 160, 22));
        getContentPane().add(card_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 130, 210, 140));

        card_cus.setPanelColor(new Color(0xE0D4FA));
        card_cus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        lbl_cusValue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32));
        lbl_cusValue.setForeground(Theme.TEXT_DARK);
        lbl_cusValue.setText("0");
        card_cus.add(lbl_cusValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));
        lbl_cusCaption.setFont(Theme.FONT_LABEL);
        lbl_cusCaption.setForeground(Theme.TEXT_DARK);
        lbl_cusCaption.setText("Customers");
        card_cus.add(lbl_cusCaption, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 160, 22));
        getContentPane().add(card_cus, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 130, 210, 140));

        card_user.setPanelColor(new Color(0xFAD4E4));
        card_user.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        lbl_userValue.setFont(new java.awt.Font("Segoe UI Semibold", 0, 32));
        lbl_userValue.setForeground(Theme.TEXT_DARK);
        lbl_userValue.setText("0");
        card_user.add(lbl_userValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, 40));
        lbl_userCaption.setFont(Theme.FONT_LABEL);
        lbl_userCaption.setForeground(Theme.TEXT_DARK);
        lbl_userCaption.setText("Users");
        card_user.add(lbl_userCaption, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 78, 160, 22));
        getContentPane().add(card_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 210, 140));

        pack();
        setSize(new java.awt.Dimension(1200, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_ManageProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageProActionPerformed
        Manage_product b = new Manage_product();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ManageProActionPerformed

    private void btn_ManageCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ManageCatActionPerformed
        Manage_category b = new Manage_category();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_ManageCatActionPerformed

    private void btn_manageCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageCusActionPerformed
        Manage_customer b = new Manage_customer();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_manageCusActionPerformed

    private void btn_manageOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageOrderActionPerformed
        Manage_order b = new Manage_order();
        b.setVisible(true);
        dispose();

    }//GEN-LAST:event_btn_manageOrderActionPerformed

    private void btn_manageUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manageUserActionPerformed
        Manage_user b = new Manage_user();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_manageUserActionPerformed

    private void btn_View_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_View_orderActionPerformed
        View_order b = new View_order();
        b.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_View_orderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Admin().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ManageCat;
    private javax.swing.JButton btn_ManagePro;
    private javax.swing.JButton btn_View_order;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_manageCus;
    private javax.swing.JButton btn_manageOrder;
    private javax.swing.JButton btn_manageUser;
    private RoundedPanel card_cat;
    private RoundedPanel card_cus;
    private RoundedPanel card_pro;
    private RoundedPanel card_user;
    private javax.swing.JLabel lbl_brand;
    private javax.swing.JLabel lbl_catCaption;
    private javax.swing.JLabel lbl_catValue;
    private javax.swing.JLabel lbl_cusCaption;
    private javax.swing.JLabel lbl_cusValue;
    private javax.swing.JLabel lbl_head;
    private javax.swing.JLabel lbl_proCaption;
    private javax.swing.JLabel lbl_proValue;
    private javax.swing.JLabel lbl_sub;
    private javax.swing.JLabel lbl_userCaption;
    private javax.swing.JLabel lbl_userValue;
    private javax.swing.JPanel pnl_sidebar;
    // End of variables declaration//GEN-END:variables

}
