/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.TableModel;
import java.awt.Color;

/**
 *
 * @author ASUS
 */
public class Dashboard_Admin1 extends javax.swing.JFrame {

    private int appuserPK = 0;

    /**
     * Creates new form Dashboard
     */
    JDBC stephan;

    public Dashboard_Admin1() {
        stephan = new JDBC();
        initComponents();
        setLocationRelativeTo(null);
    }

    private boolean ValidateFields(String formType) {
        return formType.equals("edit") && (txt_type.getText().isEmpty() || txt_name.getText().isEmpty() || txt_price.getText().isEmpty());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_head = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbl_admin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_search = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn_add1 = new javax.swing.JButton();
        btn_add2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_display = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txt_type = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        lbl_type = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_price = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_head.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        lbl_head.setForeground(new java.awt.Color(255, 255, 255));
        lbl_head.setText("Dashboard");
        jPanel1.add(lbl_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 290, -1));

        jLabel6.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, -1));

        lbl_admin.setFont(new java.awt.Font("Unispace", 1, 29)); // NOI18N
        lbl_admin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_admin.setText("Admin");
        jPanel1.add(lbl_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, -1, -1));

        btn_save.setBackground(new java.awt.Color(0, 204, 204));
        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel2.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, -1));

        btn_update.setBackground(new java.awt.Color(204, 204, 255));
        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 100, -1));

        btn_search.setBackground(new java.awt.Color(51, 153, 255));
        btn_search.setText("Search");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        jPanel2.add(btn_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 100, -1));

        btn_delete.setBackground(new java.awt.Color(255, 153, 153));
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 100, -1));

        jButton1.setText("Refresh");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 500, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 220, 750));

        btn_add1.setBackground(new java.awt.Color(153, 153, 153));
        btn_add1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_add1.setForeground(new java.awt.Color(255, 255, 255));
        btn_add1.setText("Add Furniture");
        jPanel1.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, -1));

        btn_add2.setBackground(new java.awt.Color(153, 153, 153));
        btn_add2.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_add2.setForeground(new java.awt.Color(255, 255, 255));
        btn_add2.setText("Add Furniture");
        jPanel1.add(btn_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, -1));

        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        tbl_display.setBackground(new java.awt.Color(204, 204, 204));
        tbl_display.setFont(new java.awt.Font("Elephant", 0, 18)); // NOI18N
        tbl_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Type", "Name", "price"
            }
        ));
        tbl_display.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_displayPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_display);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 870, 260));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, -1, -1));
        jPanel1.add(txt_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 150, -1));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, 150, -1));
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 150, -1));

        lbl_type.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        lbl_type.setForeground(new java.awt.Color(255, 255, 255));
        lbl_type.setText("Type");
        jPanel1.add(lbl_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, -1, -1));

        lbl_name.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Name");
        jPanel1.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 430, -1, -1));

        lbl_price.setFont(new java.awt.Font("Unispace", 0, 14)); // NOI18N
        lbl_price.setForeground(new java.awt.Color(255, 255, 255));
        lbl_price.setText("Price");
        jPanel1.add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/furniture back.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 1060, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String Type = txt_type.getText();
        String Name = txt_name.getText();
        String Price = txt_price.getText();

        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement(
                    "UPDATE furniture SET type = ?, price = ? WHERE name = ?"
            );

            pst.setString(1, Type);
            pst.setString(2, Price);
            pst.setString(3, Name);

            int rs = pst.executeUpdate();

            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Update success");
                txt_type.setText("");
                txt_name.setText("");
                txt_price.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "No record found with the provided name.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed

        String Type = txt_type.getText();
        String Name = txt_name.getText();
        String Price = txt_price.getText();

        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement("INSERT INTO furniture (type, name, price) VALUES (?, ?, ?)");

            pst.setString(1, Type);
            pst.setString(2, Name);
            pst.setString(3, Price);
            int rs = pst.executeUpdate();

            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Save success");
                txt_type.setText("");
                txt_name.setText("");
                txt_price.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void tbl_displayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_displayPropertyChange
        DefaultTableModel model = (DefaultTableModel) tbl_display.getModel();
        model.setRowCount(0);
        try {
            Connection con = stephan.connectdb();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection failed.");
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM furniture ");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("id"),
                    rs.getString("type"),
                    rs.getString("name"),
                    rs.getString("price")
                });
            }
            
        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
         
        }


    }//GEN-LAST:event_tbl_displayPropertyChange

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        int selectedRow = tbl_display.getSelectedRow();

        if (selectedRow >= 0) { 
            String type = (String) tbl_display.getValueAt(selectedRow, 0);
            String name = (String) tbl_display.getValueAt(selectedRow, 1);
            String price = (String) tbl_display.getValueAt(selectedRow, 2);

            txt_type.setText(type);
            txt_name.setText(name);
            txt_price.setText(price);
        } else {
            JOptionPane.showMessageDialog(null, "Please select a valid row.");
        }

    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String type = txt_type.getText();

        try {

            PreparedStatement pst = stephan.connectdb().prepareStatement("SELECT * FROM furniture WHERE type=? ");
            pst.setString(1, type);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                String Type = rs.getString("Type");
                String Name = rs.getString("Name");
                String Price = rs.getString("Price");

                txt_type.setText(Type);
                txt_name.setText(Name);
                txt_price.setText(Price);
            }
        } catch (Exception e) {
            e.printStackTrace();

        }
    }//GEN-LAST:event_btn_searchActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        String name = txt_name.getText();

        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement("DELETE from furniture WHERE name= ? ");
            pst.setString(1, name);

            int rs = pst.executeUpdate();
            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Delete successfully");

            } else {
                System.out.println("" + "Not Save");
            }
        } catch (Exception e) {
            System.out.println("" + e);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Dashboard_Admin1 b = new Dashboard_Admin1();
        b.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_Admin1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_Admin1().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_add2;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_admin;
    private javax.swing.JLabel lbl_head;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JTable tbl_display;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_type;
    // End of variables declaration//GEN-END:variables

}
