/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Dashboard_StoreManager extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard_StoreManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_head = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_requests = new javax.swing.JButton();
        btn_pay = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btn_logout = new javax.swing.JButton();
        btn_reserve = new javax.swing.JButton();
        btn_add2 = new javax.swing.JButton();
        lbl_admin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_add1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_head.setFont(new java.awt.Font("Unispace", 1, 48)); // NOI18N
        lbl_head.setForeground(new java.awt.Color(255, 255, 255));
        lbl_head.setText("Dashboard");
        jPanel1.add(lbl_head, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 290, -1));

        jLabel6.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, -1));

        btn_update.setBackground(new java.awt.Color(153, 153, 153));
        btn_update.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update Furniture");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel1.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 220, -1));

        btn_delete.setBackground(new java.awt.Color(153, 153, 153));
        btn_delete.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete Furniture");
        jPanel1.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 220, -1));

        btn_requests.setBackground(new java.awt.Color(153, 153, 153));
        btn_requests.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_requests.setForeground(new java.awt.Color(255, 255, 255));
        btn_requests.setText("Accept Requests");
        jPanel1.add(btn_requests, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 220, -1));

        btn_pay.setBackground(new java.awt.Color(153, 153, 153));
        btn_pay.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_pay.setForeground(new java.awt.Color(255, 255, 255));
        btn_pay.setText("Payment Details");
        jPanel1.add(btn_pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 220, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_logout.setBackground(new java.awt.Color(255, 51, 51));
        btn_logout.setFont(new java.awt.Font("Unispace", 1, 14)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Log Out");
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, -1, -1));

        btn_reserve.setBackground(new java.awt.Color(153, 153, 153));
        btn_reserve.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_reserve.setForeground(new java.awt.Color(255, 255, 255));
        btn_reserve.setText("Reserve Furniture");
        jPanel2.add(btn_reserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 220, -1));

        btn_add2.setBackground(new java.awt.Color(153, 153, 153));
        btn_add2.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_add2.setForeground(new java.awt.Color(255, 255, 255));
        btn_add2.setText("Add Furniture");
        jPanel2.add(btn_add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, -1));

        lbl_admin.setFont(new java.awt.Font("Unispace", 1, 26)); // NOI18N
        lbl_admin.setForeground(new java.awt.Color(255, 255, 255));
        lbl_admin.setText("Store Manager");
        jPanel2.add(lbl_admin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 210, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 220, 740));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/furniture back.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, -1, 700));

        btn_add1.setBackground(new java.awt.Color(153, 153, 153));
        btn_add1.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        btn_add1.setForeground(new java.awt.Color(255, 255, 255));
        btn_add1.setText("Add Furniture");
        jPanel1.add(btn_add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 210, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        this.dispose();
        Login login = new Login();
        login.setVisible(true);
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_StoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_StoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_StoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_StoreManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_StoreManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add1;
    private javax.swing.JButton btn_add2;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_pay;
    private javax.swing.JButton btn_requests;
    private javax.swing.JButton btn_reserve;
    private javax.swing.JButton btn_update;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_admin;
    private javax.swing.JLabel lbl_head;
    // End of variables declaration//GEN-END:variables
}
