/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ASUS
 */
public class Invoice extends javax.swing.JFrame {

    /**
     * Creates new form Invoice
     */
    JDBC stephan;
    
    public Invoice() {
        stephan = new JDBC();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        Quantity = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        lbl_price = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        lbl_description = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        lbl_catName = new javax.swing.JLabel();
        txt_cate = new javax.swing.JTextField();
        btn_addtocart = new javax.swing.JButton();
        lbl_total = new javax.swing.JLabel();
        lbl_final = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Unispace", 1, 24)); // NOI18N
        jLabel1.setText("Invoice");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 180, -1));

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Quantity", "Price", "Description", "Category Name"
            }
        ));
        tbl_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productMouseClicked(evt);
            }
        });
        tbl_product.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_productPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_product);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 520, 320));

        jLabel2.setText("Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 110, -1));
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 210, -1));

        Quantity.setText("Quantity");
        jPanel1.add(Quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 180, -1, -1));
        jPanel1.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 230, -1));

        lbl_price.setText("Price");
        jPanel1.add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 60, -1));
        jPanel1.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 320, 270, -1));

        lbl_description.setText("Description");
        jPanel1.add(lbl_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 80, -1));
        jPanel1.add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 420, 260, -1));

        lbl_catName.setText("category Name");
        jPanel1.add(lbl_catName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 140, -1));
        jPanel1.add(txt_cate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 510, 260, -1));

        btn_addtocart.setText("Add to cart");
        btn_addtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addtocartActionPerformed(evt);
            }
        });
        jPanel1.add(btn_addtocart, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 560, 200, -1));

        lbl_total.setText("Total price");
        jPanel1.add(lbl_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 60, -1));

        lbl_final.setText("0000000");
        jPanel1.add(lbl_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productMouseClicked
        int index  = tbl_product.getSelectedRow();
        TableModel model = tbl_product.getModel();

        String name = model.getValueAt(index, 1).toString();
        txt_name.setText(name);

        String quantity = model.getValueAt(index, 2).toString();
        txt_quantity.setText(quantity);

        String price = model.getValueAt(index, 3).toString();
        txt_price.setText(price);

        String description = model.getValueAt(index, 4).toString();
        txt_description.setText(description);
        
        String category = model.getValueAt(index, 5).toString();
        txt_cate.setText(category);

    }//GEN-LAST:event_tbl_productMouseClicked

    private void tbl_productPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_productPropertyChange
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        try {
            Connection con = stephan.connectdb();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection failed.");
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM manage_pro ");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Id"),
                    rs.getString("Name"),
                    rs.getString("Quantity"),
                    rs.getString("Price"),
                    rs.getString("Description"),
                    rs.getString("cat_name")

                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());

        }
    }//GEN-LAST:event_tbl_productPropertyChange

    private void btn_addtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addtocartActionPerformed
        
    }//GEN-LAST:event_btn_addtocartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Invoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Invoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Quantity;
    private javax.swing.JButton btn_addtocart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_catName;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_final;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_total;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_cate;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
