/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;


/**
 *
 * @author ASUS
 */
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    JDBC stephan;

    public Login() {
        stephan = new JDBC();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnl_brand = new javax.swing.JPanel();
        lbl_brand = new javax.swing.JLabel();
        lbl_tagline = new javax.swing.JLabel();
        lbl_brandImage = new javax.swing.JLabel();
        pnl_card = new RoundedPanel();
        lbl_welcome = new javax.swing.JLabel();
        lbl_subtitle = new javax.swing.JLabel();
        lbl_user = new javax.swing.JLabel();
        cmb_user = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setBackground(Theme.BG);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_brand.setBackground(Theme.PRIMARY);
        pnl_brand.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_brand.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26));
        lbl_brand.setForeground(java.awt.Color.WHITE);
        lbl_brand.setText("Furniture Co.");
        pnl_brand.add(lbl_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 300, 40));

        lbl_tagline.setFont(Theme.FONT_BODY);
        lbl_tagline.setForeground(new java.awt.Color(224, 224, 250));
        lbl_tagline.setText("<html>Manage inventory, orders<br>and customers in one place.</html>");
        pnl_brand.add(lbl_tagline, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 95, 300, 50));

        lbl_brandImage.setIcon(new javax.swing.ImageIcon(
            new javax.swing.ImageIcon(getClass().getResource("/resources/login.jpg"))
                .getImage().getScaledInstance(380, 280, java.awt.Image.SCALE_SMOOTH)));
        pnl_brand.add(lbl_brandImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 380, 280));

        getContentPane().add(pnl_brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 580));

        pnl_card.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_welcome.setFont(Theme.FONT_TITLE);
        lbl_welcome.setForeground(Theme.TEXT_DARK);
        lbl_welcome.setText("Welcome back");
        pnl_card.add(lbl_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 300, 40));

        lbl_subtitle.setFont(Theme.FONT_BODY);
        lbl_subtitle.setForeground(Theme.TEXT_MUTED);
        lbl_subtitle.setText("Sign in to continue");
        pnl_card.add(lbl_subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 78, 300, 24));

        lbl_user.setFont(Theme.FONT_LABEL);
        lbl_user.setForeground(Theme.TEXT_MUTED);
        lbl_user.setText("ROLE");
        pnl_card.add(lbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 300, 18));

        cmb_user.setFont(Theme.FONT_BODY);
        cmb_user.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Store Manager", "WareHouse Staff", "Inventory", "Customer" }));
        cmb_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_userActionPerformed(evt);
            }
        });
        pnl_card.add(cmb_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 162, 300, 38));

        jLabel2.setFont(Theme.FONT_LABEL);
        jLabel2.setForeground(Theme.TEXT_MUTED);
        jLabel2.setText("PASSWORD");
        pnl_card.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 216, 300, 18));
        pnl_card.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 238, 300, 38));

        btn_login.setText("Login");
        Theme.primaryButton(btn_login);
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        pnl_card.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 300, 44));

        btn_close.setText("Exit");
        Theme.secondaryButton(btn_close);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });
        pnl_card.add(btn_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 356, 300, 40));

        getContentPane().add(pnl_card, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 380, 420));

        pack();
        setSize(new java.awt.Dimension(900, 580));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
      cmb_user.setSelectedIndex(0);
        txt_pass.setText("");

        dispose();
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        String username = (String) cmb_user.getSelectedItem();
        String pass = new String(txt_pass.getPassword());
        String useranme = "Mevan";

        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement("Select * From fms.login where username=? and pass=?");
            pst.setString(1, username);
            pst.setString(2, pass);
            ResultSet rs = pst.executeQuery();
            if (rs.next()) {
                String username_2 = rs.getString("username");
                if (username_2.equalsIgnoreCase("Admin")) {
                    Dashboard_Admin b = new Dashboard_Admin();
                    b.setVisible(true);
                }else if(username_2.equalsIgnoreCase("Store Manager")) {
                    Dashboard_StoreManager b = new Dashboard_StoreManager();
                    b.setVisible(true);
                }else if(username_2.equalsIgnoreCase("Inventory")) {
                    Dashboard_InventoryClerk b = new Dashboard_InventoryClerk();
                    b.setVisible(true);
                }else if(username_2.equalsIgnoreCase("WareHouse Staff")) {
                    Dashboard_WareHouseStaff b = new Dashboard_WareHouseStaff();
                    b.setVisible(true);
                }else if(username_2.equalsIgnoreCase("Customer")) {
                    Invoice b = new Invoice();
                    b.setVisible(true);
                }

                dispose();


            } else {
                JOptionPane.showMessageDialog(rootPane, "Login failed. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void cmb_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();
        javax.swing.UIManager.put("Button.arc", 14);
        javax.swing.UIManager.put("Component.arc", 10);
        javax.swing.UIManager.put("TextComponent.arc", 10);
        javax.swing.UIManager.put("ScrollBar.thumbArc", 999);
        javax.swing.UIManager.put("ScrollBar.width", 12);
        javax.swing.UIManager.put("Table.rowHeight", 32);
        javax.swing.UIManager.put("Component.focusColor", Theme.PRIMARY);
        javax.swing.UIManager.put("Component.focusedBorderColor", Theme.PRIMARY);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_close;
    private javax.swing.JButton btn_login;
    private javax.swing.JComboBox<String> cmb_user;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_brand;
    private javax.swing.JLabel lbl_brandImage;
    private javax.swing.JLabel lbl_subtitle;
    private javax.swing.JLabel lbl_tagline;
    private javax.swing.JLabel lbl_user;
    private javax.swing.JLabel lbl_welcome;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JPanel pnl_brand;
    private RoundedPanel pnl_card;
    // End of variables declaration//GEN-END:variables
}
