/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ASUS
 */
public class Manage_product extends javax.swing.JFrame {

    /**
     * Creates new form Manage_product
     */
        JDBC stephan;

    public Manage_product() {
        stephan = new JDBC();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        card_table = new RoundedPanel();
        lbl_listHeading = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_display = new javax.swing.JTable();
        card_form = new RoundedPanel();
        lbl_formHeading = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_quantity = new javax.swing.JLabel();
        txt_quantity = new javax.swing.JTextField();
        lbl_price = new javax.swing.JLabel();
        txt_price = new javax.swing.JTextField();
        lbl_description = new javax.swing.JLabel();
        txt_description = new javax.swing.JTextField();
        lbl_category = new javax.swing.JLabel();
        combo_category = new javax.swing.JComboBox<>();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setBackground(Theme.BG);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setText("← Back");
        Theme.secondaryButton(btn_back);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 110, 40));

        lbl_title.setFont(Theme.FONT_TITLE);
        lbl_title.setForeground(Theme.TEXT_DARK);
        lbl_title.setText("Manage Product");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 24, 360, 40));

        card_table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_listHeading.setFont(Theme.FONT_HEADING);
        lbl_listHeading.setForeground(Theme.TEXT_DARK);
        lbl_listHeading.setText("Product List");
        card_table.add(lbl_listHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 300, 28));

        jButton1.setText("Refresh");
        Theme.secondaryButton(jButton1);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        card_table.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 14, 100, 38));

        tbl_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Quantity", "Price", "Description", "Category Name"
            }
        ));
        tbl_display.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_displayPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_display);

        card_table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, 556, 400));

        getContentPane().add(card_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 604, 490));

        card_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_formHeading.setFont(Theme.FONT_HEADING);
        lbl_formHeading.setForeground(Theme.TEXT_DARK);
        lbl_formHeading.setText("Add / Edit Product");
        card_form.add(lbl_formHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 260, 26));

        lbl_name.setFont(Theme.FONT_LABEL);
        lbl_name.setForeground(Theme.TEXT_MUTED);
        lbl_name.setText("NAME");
        card_form.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 58, 260, 16));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        card_form.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 76, 260, 32));

        lbl_quantity.setFont(Theme.FONT_LABEL);
        lbl_quantity.setForeground(Theme.TEXT_MUTED);
        lbl_quantity.setText("QUANTITY");
        card_form.add(lbl_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 118, 260, 16));
        card_form.add(txt_quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 136, 260, 32));

        lbl_price.setFont(Theme.FONT_LABEL);
        lbl_price.setForeground(Theme.TEXT_MUTED);
        lbl_price.setText("PRICE");
        card_form.add(lbl_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 178, 260, 16));
        card_form.add(txt_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 196, 260, 32));

        lbl_description.setFont(Theme.FONT_LABEL);
        lbl_description.setForeground(Theme.TEXT_MUTED);
        lbl_description.setText("DESCRIPTION");
        card_form.add(lbl_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 238, 260, 16));
        card_form.add(txt_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 256, 260, 32));

        lbl_category.setFont(Theme.FONT_LABEL);
        lbl_category.setForeground(Theme.TEXT_MUTED);
        lbl_category.setText("CATEGORY");
        card_form.add(lbl_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 298, 260, 16));

        combo_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", " " }));
        card_form.add(combo_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 316, 260, 32));

        btn_save.setText("Save");
        Theme.primaryButton(btn_save);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        card_form.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 362, 260, 38));

        btn_update.setText("Update");
        Theme.secondaryButton(btn_update);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        card_form.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 406, 260, 38));

        btn_cancel.setText("Reset");
        Theme.secondaryButton(btn_cancel);
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });
        card_form.add(btn_cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 450, 260, 38));

        getContentPane().add(card_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 90, 316, 490));

        pack();
        setSize(new java.awt.Dimension(1010, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Dashboard_Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        txt_name.setText("");
        txt_quantity.setText("");
        txt_price.setText("");
        txt_description.setText("");
        combo_category.setSelectedIndex(0);

        JOptionPane.showMessageDialog(null, "fields are cleared");
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String Name = txt_name.getText();
        String quantity = txt_quantity.getText();
        String Price = txt_price.getText();
        String Descrip = txt_description.getText();
        String cat_name = (String) combo_category.getSelectedItem();
        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement(
                    "UPDATE Manage_pro SET quantity = ?, price = ?, description = ?, cat_name = ? WHERE name = ?"
            );

            pst.setString(1, Name);
            pst.setString(2, quantity);
            pst.setString(3, Price);
            pst.setString(4, Descrip);
            pst.setString(5, cat_name);

            int rs = pst.executeUpdate();

            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Update success");
                txt_name.setText("");
                txt_quantity.setText("");
                txt_price.setText("");
                txt_description.setText("");
                combo_category.setSelectedIndex(0);
            } else {
                JOptionPane.showMessageDialog(null, "No record found with the provided name.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String Name = txt_name.getText();
        String quantity = txt_quantity.getText();
        String price = txt_price.getText();
        String description = txt_description.getText();
        String cat_name = (String) combo_category.getSelectedItem();

        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement("INSERT INTO manage_pro (Name, Quantity, Price, Description, Cat_name ) VALUES (?, ?, ?, ?, ?)");

            pst.setString(1, Name);
            pst.setString(2, quantity);
            pst.setString(3, price);
            pst.setString(4, description);
            pst.setString(5, cat_name);
            int rs = pst.executeUpdate();

            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Save success");
                txt_name.setText("");
                txt_quantity.setText("");
                txt_price.setText("");
                txt_description.setText("");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void tbl_displayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_displayPropertyChange
        DefaultTableModel model = (DefaultTableModel) tbl_display.getModel();
        model.setRowCount(0);
        try {
            Connection con = stephan.connectdb();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection failed.");
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM manage_pro ");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Id"),
                    rs.getString("Name"),
                    rs.getString("Quantity"),
                    rs.getString("Price"),
                    rs.getString("Description"),
                    rs.getString("cat_name")


                });
            }

        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());

        }
    }//GEN-LAST:event_tbl_displayPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        Manage_product b = new Manage_product();
        b.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private RoundedPanel card_form;
    private RoundedPanel card_table;
    private javax.swing.JComboBox<String> combo_category;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_category;
    private javax.swing.JLabel lbl_description;
    private javax.swing.JLabel lbl_formHeading;
    private javax.swing.JLabel lbl_listHeading;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_price;
    private javax.swing.JLabel lbl_quantity;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTable tbl_display;
    private javax.swing.JTextField txt_description;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_quantity;
    // End of variables declaration//GEN-END:variables
}
