/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.table.TableModel;


/**
 *
 * @author ASUS
 */
public class Manage_order extends javax.swing.JFrame {

    private int customerPK = 0;
    private int ProductPK = 0;
    private int FinalTotalPrice = 0;
    private String orderID = "";


    /**
     * Creates new form Manage_order
     */

    JDBC stephan;
    public Manage_order() {
        stephan =  new JDBC();
        initComponents();
        setLocationRelativeTo(null);
    }

    private void clearProductFields (){
        ProductPK = 0;
        txt_proName.setText("");
        txt_proPrice.setText("");
        txt_proDescription.setText("");
        txt_orderQuan.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        card_customer = new RoundedPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_customer = new javax.swing.JTable();
        lbl_cusTitle = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_cusName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_cusMobile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cusEmail = new javax.swing.JTextField();
        card_product = new RoundedPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        lbl_proTitle = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_proName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_proPrice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_proDescription = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_orderQuan = new javax.swing.JTextField();
        btn_addToCart = new javax.swing.JButton();
        card_cart = new RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        table_cart = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        lbl_finalTotal = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setBackground(Theme.BG);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setText("← Back");
        Theme.secondaryButton(btn_back);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 110, 40));

        lbl_title.setFont(Theme.FONT_TITLE);
        lbl_title.setForeground(Theme.TEXT_DARK);
        lbl_title.setText("Manage Order");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 24, 360, 40));

        card_customer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(Theme.FONT_HEADING);
        jLabel13.setForeground(Theme.TEXT_DARK);
        jLabel13.setText("Customers");
        card_customer.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 300, 28));

        tbl_customer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Mobile num", "Email"
            }
        ));
        tbl_customer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_customerMouseClicked(evt);
            }
        });
        tbl_customer.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_customerPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_customer);

        card_customer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 392, 260));

        lbl_cusTitle.setFont(Theme.FONT_LABEL);
        lbl_cusTitle.setForeground(Theme.TEXT_MUTED);
        lbl_cusTitle.setText("SELECTED CUSTOMER");
        card_customer.add(lbl_cusTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 336, 300, 20));

        jLabel3.setFont(Theme.FONT_LABEL);
        jLabel3.setForeground(Theme.TEXT_MUTED);
        jLabel3.setText("NAME");
        card_customer.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 368, 200, 16));
        card_customer.add(txt_cusName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 386, 392, 32));

        jLabel4.setFont(Theme.FONT_LABEL);
        jLabel4.setForeground(Theme.TEXT_MUTED);
        jLabel4.setText("MOBILE NUMBER");
        card_customer.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 428, 200, 16));
        card_customer.add(txt_cusMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 446, 392, 32));

        jLabel5.setFont(Theme.FONT_LABEL);
        jLabel5.setForeground(Theme.TEXT_MUTED);
        jLabel5.setText("EMAIL");
        card_customer.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 488, 200, 16));
        card_customer.add(txt_cusEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 506, 392, 32));

        getContentPane().add(card_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 440, 670));

        card_product.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(Theme.FONT_HEADING);
        jLabel15.setForeground(Theme.TEXT_DARK);
        jLabel15.setText("Products");
        card_product.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 300, 28));

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Quantity", "Price", "Description", "Category Name"
            }
        ));
        tbl_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productMouseClicked(evt);
            }
        });
        tbl_product.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_productPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_product);

        card_product.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 392, 260));

        lbl_proTitle.setFont(Theme.FONT_LABEL);
        lbl_proTitle.setForeground(Theme.TEXT_MUTED);
        lbl_proTitle.setText("SELECTED PRODUCT");
        card_product.add(lbl_proTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 336, 300, 20));

        jLabel8.setFont(Theme.FONT_LABEL);
        jLabel8.setForeground(Theme.TEXT_MUTED);
        jLabel8.setText("PRODUCT NAME");
        card_product.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 368, 200, 16));
        card_product.add(txt_proName, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 386, 392, 32));

        jLabel9.setFont(Theme.FONT_LABEL);
        jLabel9.setForeground(Theme.TEXT_MUTED);
        jLabel9.setText("PRODUCT PRICE");
        card_product.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 428, 200, 16));
        card_product.add(txt_proPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 446, 392, 32));

        jLabel10.setFont(Theme.FONT_LABEL);
        jLabel10.setForeground(Theme.TEXT_MUTED);
        jLabel10.setText("PRODUCT DESCRIPTION");
        card_product.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 488, 200, 16));
        card_product.add(txt_proDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 506, 392, 32));

        jLabel11.setFont(Theme.FONT_LABEL);
        jLabel11.setForeground(Theme.TEXT_MUTED);
        jLabel11.setText("ORDER QUANTITY");
        card_product.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 548, 200, 16));
        card_product.add(txt_orderQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 566, 392, 32));

        btn_addToCart.setText("Add To Cart");
        Theme.primaryButton(btn_addToCart);
        btn_addToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addToCartActionPerformed(evt);
            }
        });
        card_product.add(btn_addToCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 610, 392, 40));

        getContentPane().add(card_product, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 440, 670));

        card_cart.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(Theme.FONT_HEADING);
        jLabel2.setForeground(Theme.TEXT_DARK);
        jLabel2.setText("Cart");
        card_cart.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 300, 28));

        table_cart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Name", "Qauntity", "Price", "Description", "Sub total"
            }
        ));
        table_cart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_cartMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(table_cart);

        card_cart.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 60, 452, 430));

        jLabel12.setFont(Theme.FONT_LABEL);
        jLabel12.setForeground(Theme.TEXT_MUTED);
        jLabel12.setText("TOTAL AMOUNT (Rs)");
        card_cart.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 506, 250, 20));

        lbl_finalTotal.setFont(new java.awt.Font("Segoe UI Semibold", 0, 26));
        lbl_finalTotal.setForeground(Theme.TEXT_DARK);
        lbl_finalTotal.setText("0");
        card_cart.add(lbl_finalTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 528, 250, 36));

        btn_reset.setText("Reset");
        Theme.secondaryButton(btn_reset);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        card_cart.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 578, 452, 40));

        getContentPane().add(card_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 90, 500, 670));

        pack();
        setSize(new java.awt.Dimension(1500, 810));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Dashboard_Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void tbl_customerPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_customerPropertyChange
        txt_cusName.setEditable(false);
        txt_cusMobile.setEditable(false);
        txt_cusEmail.setEditable(false);

        txt_proName.setEditable(false);
        txt_proPrice.setEditable(false);
        txt_proDescription.setEditable(false);


        DefaultTableModel model = (DefaultTableModel) tbl_customer.getModel();
        DefaultTableModel productmodel = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        try {
            Connection con = stephan.connectdb();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection failed.");
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM customer ");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Id"),
                    rs.getString("Name"),
                    rs.getString("Mobile num"),
                    rs.getString("Email"),

                });
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());

        }
    }//GEN-LAST:event_tbl_customerPropertyChange

    private void tbl_productPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_productPropertyChange
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        try {
            Connection con = stephan.connectdb();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection failed.");
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM manage_pro ");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Id"),
                    rs.getString("Name"),
                    rs.getString("Quantity"),
                    rs.getString("Price"),
                    rs.getString("Description"),
                    rs.getString("cat_name")


                });
            }

        } catch (Exception e) {
          JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());

        }
    }//GEN-LAST:event_tbl_productPropertyChange

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
         try {
            txt_proName.setText("");
            txt_proPrice.setText("");
            txt_proDescription.setText("");
            txt_cusName.setText("");
            txt_cusMobile.setText("");
            txt_cusEmail.setText("");

            JOptionPane.showMessageDialog(null, "fields are cleared");

        } catch (Exception e) {
            System.out.println("Error while clearing + e");
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_customerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_customerMouseClicked
        int index = tbl_customer.getSelectedRow();
        TableModel model = tbl_customer.getModel();

        String name = model.getValueAt(index, 1).toString();
        txt_cusName.setText(name);

        String mobile_num = model.getValueAt(index, 2).toString();
        txt_cusMobile.setText(mobile_num);

        String email = model.getValueAt(index, 3).toString();
        txt_cusEmail.setText(email);

    }//GEN-LAST:event_tbl_customerMouseClicked

    private void tbl_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productMouseClicked
        int index  = tbl_product.getSelectedRow();
        TableModel model = tbl_product.getModel();

        String name = model.getValueAt(index, 1).toString();
        txt_proName.setText(name);

        String quantity = model.getValueAt(index, 2).toString();
        txt_orderQuan.setText(quantity);

        String price = model.getValueAt(index, 3).toString();
        txt_proPrice.setText(price);

        String description = model.getValueAt(index, 4).toString();
        txt_proDescription.setText(description);


    }//GEN-LAST:event_tbl_productMouseClicked

    private void btn_addToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addToCartActionPerformed
        String NoOfUnits = txt_orderQuan.getText();
        if (!NoOfUnits.equals("")) {
            String productName = txt_proName.getText();
            String productDescription = txt_proDescription.getText();
            String productPrice = txt_proPrice.getText();

            double totalPrice = Double.parseDouble(NoOfUnits) * Double.parseDouble(productPrice);

            int checkStock = 0;
            int checkProductAlreadyExistInCart = 0;

            try {
                Connection con = stephan.connectdb();
                Statement st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM manage_pro WHERE id = " + ProductPK);
                while (rs.next()) {
                    if (rs.getInt("quantity") >= Double.parseDouble(NoOfUnits)) {
                        checkStock = 1;
                    } else {
                        JOptionPane.showMessageDialog(null, "Product is out of stock. Only " + rs.getInt("quantity") + " left.");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
                DefaultTableModel model = (DefaultTableModel) table_cart.getModel();
            if (checkStock == 1) {
                if (table_cart.getRowCount() != 0) {
                    for (int i = 0; i < table_cart.getRowCount(); i++) {
                        checkProductAlreadyExistInCart = 1;
                        JOptionPane.showMessageDialog(null, "Product already exists in cart.");
                    }
                }
            }

            if (checkProductAlreadyExistInCart == 0) {
                model.addRow(new Object[]{ProductPK, productName, productPrice, productDescription, totalPrice});
                FinalTotalPrice = (int) (FinalTotalPrice + totalPrice);
                lbl_finalTotal.setText(String.valueOf(FinalTotalPrice));
                JOptionPane.showMessageDialog(null, "Added Successfully");
            }
            clearProductFields();
        } else {
            JOptionPane.showMessageDialog(null, "Number of units and product field is required.");
        }

    }//GEN-LAST:event_btn_addToCartActionPerformed

    private void table_cartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_cartMouseClicked
        int index = table_cart.getSelectedRow();
        TableModel model = table_cart.getModel();
        String subTotal = model.getValueAt(index, 5).toString();
        FinalTotalPrice = FinalTotalPrice - Integer.parseInt(subTotal);
        lbl_finalTotal.setText(String.valueOf(FinalTotalPrice));
        ((DefaultTableModel) table_cart.getModel()).removeRow(index);
    }//GEN-LAST:event_table_cartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addToCart;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_reset;
    private RoundedPanel card_cart;
    private RoundedPanel card_customer;
    private RoundedPanel card_product;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_cusTitle;
    private javax.swing.JLabel lbl_finalTotal;
    private javax.swing.JLabel lbl_proTitle;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTable table_cart;
    private javax.swing.JTable tbl_customer;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_cusEmail;
    private javax.swing.JTextField txt_cusMobile;
    private javax.swing.JTextField txt_cusName;
    private javax.swing.JTextField txt_orderQuan;
    private javax.swing.JTextField txt_proDescription;
    private javax.swing.JTextField txt_proName;
    private javax.swing.JTextField txt_proPrice;
    // End of variables declaration//GEN-END:variables
}
