/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Manage_customer extends javax.swing.JFrame {

    /**
     * Creates new form Manage_customer
     */
    JDBC stephan;

    public Manage_customer() {
        stephan = new JDBC();
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        card_table = new RoundedPanel();
        lbl_listHeading = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_display = new javax.swing.JTable();
        card_form = new RoundedPanel();
        lbl_formHeading = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_mobile = new javax.swing.JLabel();
        txt_mobile = new javax.swing.JTextField();
        lbl_email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_reset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setBackground(Theme.BG);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setText("← Back");
        Theme.secondaryButton(btn_back);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 110, 40));

        lbl_title.setFont(Theme.FONT_TITLE);
        lbl_title.setForeground(Theme.TEXT_DARK);
        lbl_title.setText("Manage Customer");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 24, 360, 40));

        card_table.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_listHeading.setFont(Theme.FONT_HEADING);
        lbl_listHeading.setForeground(Theme.TEXT_DARK);
        lbl_listHeading.setText("Customer List");
        card_table.add(lbl_listHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 300, 28));

        btn_refresh.setText("Refresh");
        Theme.secondaryButton(btn_refresh);
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        card_table.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 14, 100, 38));

        tbl_display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Mobile num", "Email"
            }
        ));
        tbl_display.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbl_displayPropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_display);

        card_table.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, 556, 400));

        getContentPane().add(card_table, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 604, 490));

        card_form.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_formHeading.setFont(Theme.FONT_HEADING);
        lbl_formHeading.setForeground(Theme.TEXT_DARK);
        lbl_formHeading.setText("Add / Edit Customer");
        card_form.add(lbl_formHeading, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 260, 28));

        lbl_name.setFont(Theme.FONT_LABEL);
        lbl_name.setForeground(Theme.TEXT_MUTED);
        lbl_name.setText("NAME");
        card_form.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, 260, 18));
        card_form.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 88, 260, 36));

        lbl_mobile.setFont(Theme.FONT_LABEL);
        lbl_mobile.setForeground(Theme.TEXT_MUTED);
        lbl_mobile.setText("MOBILE NUMBER");
        card_form.add(lbl_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 134, 260, 18));
        card_form.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 156, 260, 36));

        lbl_email.setFont(Theme.FONT_LABEL);
        lbl_email.setForeground(Theme.TEXT_MUTED);
        lbl_email.setText("EMAIL");
        card_form.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 202, 260, 18));
        card_form.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 224, 260, 36));

        btn_save.setText("Save");
        Theme.primaryButton(btn_save);
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        card_form.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 282, 260, 42));

        btn_update.setText("Update");
        Theme.secondaryButton(btn_update);
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        card_form.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 332, 260, 42));

        btn_reset.setText("Reset");
        Theme.secondaryButton(btn_reset);
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        card_form.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 382, 260, 42));

        getContentPane().add(card_form, new org.netbeans.lib.awtextra.AbsoluteConstraints(654, 90, 316, 490));

        pack();
        setSize(new java.awt.Dimension(1010, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Dashboard_Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        String Name = txt_name.getText();
        String Mobile = txt_mobile.getText();
        String Email = txt_email.getText();

        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement(
                    "UPDATE customer SET 'Mobile num' = ?, Email = ? WHERE Name = ?"
            );

            pst.setString(1, Mobile);
            pst.setString(2, Email);
            pst.setString(3, Name);

            int rs = pst.executeUpdate();

            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Update successful");
                txt_name.setText("");
                txt_mobile.setText("");
                txt_email.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "No record found with the provided name.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String Name = txt_name.getText();
        String mobile = txt_mobile.getText();
        String email = txt_email.getText();

        try {
            PreparedStatement pst = stephan.connectdb().prepareStatement(
                    "INSERT INTO customer (Name, `Mobile num`, Email) VALUES (?, ?, ?)"
            );

            pst.setString(1, Name);
            pst.setString(2, mobile);
            pst.setString(3, email);

            int rs = pst.executeUpdate();

            if (rs > 0) {
                JOptionPane.showMessageDialog(null, "Save success");
                txt_name.setText("");
                txt_mobile.setText("");
                txt_email.setText("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        try {
            txt_name.setText("");
            txt_mobile.setText("");
            txt_email.setText("");

            JOptionPane.showMessageDialog(null, "fields are cleared");

        } catch (Exception e) {
            System.out.println("Error while clearing + e");
        }
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tbl_displayPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbl_displayPropertyChange
        DefaultTableModel model = (DefaultTableModel) tbl_display.getModel();
        model.setRowCount(0);
        try {
            Connection con = stephan.connectdb();
            if (con == null) {
                JOptionPane.showMessageDialog(null, "Database connection failed.");
                return;
            }
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM customer ");

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("Id"),
                    rs.getString("Name"),
                    rs.getString("Mobile num"),
                    rs.getString("Email"),});
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());

        }
    }//GEN-LAST:event_tbl_displayPropertyChange

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        dispose();
        Manage_customer b = new Manage_customer();
        b.setVisible(true);
    }//GEN-LAST:event_btn_refreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private RoundedPanel card_form;
    private RoundedPanel card_table;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_formHeading;
    private javax.swing.JLabel lbl_listHeading;
    private javax.swing.JLabel lbl_mobile;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTable tbl_display;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_name;
    // End of variables declaration//GEN-END:variables
}
