/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package furniture.management.system;

/**
 *
 * @author ASUS
 */
public class View_order extends javax.swing.JFrame {

    /**
     * Creates new form View_order
     */
    public View_order() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        lbl_title = new javax.swing.JLabel();
        card_customers = new RoundedPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        card_orders = new RoundedPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setBackground(Theme.BG);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setText("← Back");
        Theme.secondaryButton(btn_back);
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 24, 110, 40));

        lbl_title.setFont(Theme.FONT_TITLE);
        lbl_title.setForeground(Theme.TEXT_DARK);
        lbl_title.setText("View Order");
        getContentPane().add(lbl_title, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 24, 360, 40));

        card_customers.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(Theme.FONT_HEADING);
        jLabel2.setForeground(Theme.TEXT_DARK);
        jLabel2.setText("Customer List");
        card_customers.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 300, 28));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Name", "Mobile  num", "Email"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        card_customers.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, 456, 400));

        getContentPane().add(card_customers, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 504, 490));

        card_orders.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(Theme.FONT_HEADING);
        jLabel1.setForeground(Theme.TEXT_DARK);
        jLabel1.setText("Order List");
        card_orders.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 20, 300, 28));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Name", "Total Paid"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        card_orders.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 66, 456, 400));

        getContentPane().add(card_orders, new org.netbeans.lib.awtextra.AbsoluteConstraints(554, 90, 504, 490));

        pack();
        setSize(new java.awt.Dimension(1110, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        new Dashboard_Admin().setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        com.formdev.flatlaf.FlatLightLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_order().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private RoundedPanel card_customers;
    private RoundedPanel card_orders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_title;
    // End of variables declaration//GEN-END:variables
}
